name: Build LootCLI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  VCPKG_BINARY_SOURCES: ${{ vars.AZ_BLOB_VCPKG_URL != '' && format('clear;x-azblob,{0},{1},readwrite', vars.AZ_BLOB_VCPKG_URL, secrets.AZ_BLOB_SAS) || '' }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install build dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libtbb-dev

      - name: Build LootCLI
        uses: Kaedras/build-with-mob-action@master
        with:
          mo2-dependencies: cmake_common
