name: Build LootCLI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  VCPKG_BINARY_SOURCES: ${{ vars.AZ_BLOB_VCPKG_URL != '' && format('clear;x-azblob,{0},{1},readwrite', vars.AZ_BLOB_VCPKG_URL, secrets.AZ_BLOB_SAS) || '' }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install build dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libtbb-dev libicu-dev

      # this step has been copied from https://github.com/loot/libloot/blob/0.26.3/.github/workflows/ci.yml
      - name: Install cbindgen
        if: runner.os == 'Linux'
        run: |
          wget https://github.com/mozilla/cbindgen/releases/download/0.28.0/cbindgen
          BIN_PATH="$HOME/.local/bin/"
          mkdir -p "$BIN_PATH"
          mv cbindgen "$BIN_PATH"
          chmod +x "$BIN_PATH/cbindgen"
          echo "$BIN_PATH" >> "$GITHUB_PATH"

      - name: Build LootCLI
        uses: Kaedras/build-with-mob-action@master
        with:
          mo2-dependencies: cmake_common
